#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef ZOOMUNIT_SWIFT_H
#define ZOOMUNIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AppKit;
@import CoreFoundation;
@import CoreGraphics;
@import Foundation;
@import ImageIO;
@import ObjectiveC;
@import Prism;
@import QuartzCore;
#endif

#import <ZoomUnit/ZoomUnit.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZoomUnit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class NSEvent;
@class NSWindow;

@interface PZPTrackingButton (SWIFT_EXTENSION(ZoomUnit))
@property (nonatomic, readonly) BOOL canBecomeKeyView;
@property (nonatomic, getter=isHidden) BOOL hidden;
@property (nonatomic) BOOL isHighlighteds;
- (void)commonInit;
- (void)updateTrackingAreas;
- (void)mouseEntered:(NSEvent * _Nonnull)event;
- (void)mouseExited:(NSEvent * _Nonnull)event;
- (void)viewWillMoveToWindow:(NSWindow * _Nullable)newWindow;
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (void)customMouseEntered;
- (void)customMouseExited;
@property (nonatomic, readonly) NSRect trackingRect;
@property (nonatomic, readonly) NSTrackingAreaOptions trackingOptions;
- (NSPoint)tooltipOriginInScreen SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidMoveToWindow;
@end

@class NSNumber;
@class NSImage;

SWIFT_CLASS_NAMED("ShareCaptureEngine")
@interface ZMShareCaptureEngine : NSObject
+ (void)captureDesktop:(NSInteger)desktopID size:(CGSize)size filterOutWinIDs:(NSArray<NSNumber *> * _Nullable)filterOutWinIDs completion:(void (^ _Nonnull)(NSImage * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ZoomUnit21ZMDeepLinkFilterModel")
@interface ZMDeepLinkFilterModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC8ZoomUnit14ZMDeepLinkInfo")
@interface ZMDeepLinkInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull deepLink;
@property (nonatomic, copy) NSString * _Nullable showName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZMDialogViewController;

SWIFT_PROTOCOL("_TtP8ZoomUnit30ZMDialogViewControllerDelegate_")
@protocol ZMDialogViewControllerDelegate
- (void)dialogViewControllerDidDismiss:(ZMDialogViewController * _Nonnull)sender;
@end

@class ZMDialogOptions;

SWIFT_CLASS("_TtC8ZoomUnit14ZMDialogHelper")
@interface ZMDialogHelper : NSObject <ZMDialogViewControllerDelegate>
+ (ZMDialogHelper * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)showAlertWithOptions:(ZMDialogOptions * _Nonnull)options inWindow:(NSWindow * _Nullable)window;
- (void)dialogViewControllerDidDismiss:(ZMDialogViewController * _Nonnull)sender;
@end

enum ZMDialogViewControllerStyle : NSInteger;

SWIFT_CLASS("_TtC8ZoomUnit15ZMDialogOptions")
@interface ZMDialogOptions : NSObject
@property (nonatomic) enum ZMDialogViewControllerStyle style;
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSImage * _Nullable titleIcon;
@property (nonatomic, copy) void (^ _Nullable primaryAction)(ZMDialogViewController * _Nonnull);
@property (nonatomic, copy) NSString * _Nullable primaryActionText;
@property (nonatomic, copy) void (^ _Nullable secondaryAction)(ZMDialogViewController * _Nonnull);
@property (nonatomic, copy) NSString * _Nullable secondaryActionText;
@property (nonatomic, copy) NSString * _Nullable linkURL;
@property (nonatomic, copy) NSString * _Nullable linkText;
@property (nonatomic, copy) NSString * _Nullable footnote;
@property (nonatomic, copy) NSString * _Nullable checkboxText;
@property (nonatomic) BOOL showCloseButton;
@property (nonatomic, copy) void (^ _Nullable closeButtonHandler)(void);
- (nonnull instancetype)initWithStyle:(enum ZMDialogViewControllerStyle)style body:(NSString * _Nonnull)body OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;
@class NSBundle;

SWIFT_CLASS("_TtC8ZoomUnit22ZMDialogViewController")
@interface ZMDialogViewController : NSViewController
@property (nonatomic, weak) id <ZMDialogViewControllerDelegate> _Nullable delegate;
@property (nonatomic) enum ZMDialogViewControllerStyle style;
@property (nonatomic, copy) NSString * _Nonnull body;
@property (nonatomic, copy) NSString * _Nullable dialogTitle;
@property (nonatomic, strong) NSImage * _Nullable titleIcon;
@property (nonatomic, copy) NSString * _Nullable footnote;
@property (nonatomic, copy) NSString * _Nullable checkboxLabel;
@property (nonatomic) BOOL showCloseButton;
@property (nonatomic, readonly, copy) NSNibName _Nullable nibName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithNibName:(NSNibName _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)close;
- (void)showIn:(NSWindow * _Nullable)_window;
- (void)setPrimaryAction:(void (^ _Nullable)(ZMDialogViewController * _Nonnull))action text:(NSString * _Nullable)text;
- (void)setSecondaryAction:(void (^ _Nullable)(ZMDialogViewController * _Nonnull))action text:(NSString * _Nullable)text;
- (void)setLinkWithUrl:(NSString * _Nullable)url label:(NSString * _Nullable)label;
@end


typedef SWIFT_ENUM(NSInteger, ZMDialogViewControllerStyle, closed) {
  ZMDialogViewControllerStyleNarrow = 0,
  ZMDialogViewControllerStyleWide = 1,
};


SWIFT_CLASS("_TtC8ZoomUnit13ZMGiftV2Model")
@interface ZMGiftV2Model : NSObject
@property (nonatomic, copy) NSString * _Nullable videoPath;
@property (nonatomic, strong) NSImage * _Nullable videoThumbnail;
@property (nonatomic, strong) NSImage * _Nullable giftImage;
@property (nonatomic) NSInteger giftImageIndex;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable primaryTitle;
@property (nonatomic, copy) NSString * _Nullable primaryUrl;
@property (nonatomic, copy) NSString * _Nullable secondaryTitle;
@property (nonatomic, copy) NSString * _Nullable secondaryUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ZoomUnit13ZMGiftV2Panel")
@interface ZMGiftV2Panel : ZMInvisiblePlainWindow
- (nonnull instancetype)initWithModel:(ZMGiftV2Model * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
- (void)cleanUp;
- (void)cancelOperation:(id _Nullable)sender;
- (nonnull instancetype)initWithContentRect:(NSRect)contentRect closable:(BOOL)closable miniaturizable:(BOOL)miniaturizable resizable:(BOOL)resizable generateWidgets:(BOOL)generate SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithContentRect:(NSRect)contentRect styleMask:(NSWindowStyleMask)style backing:(NSBackingStoreType)backingStoreType defer:(BOOL)flag SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP8ZoomUnit21ZMGiftV2PanelDelegate_")
@protocol ZMGiftV2PanelDelegate <NSWindowDelegate>
@optional
- (void)windowDidClickPrimaryButton:(ZMGiftV2Panel * _Nonnull)panel;
- (void)windowDidClickSecondaryButton:(ZMGiftV2Panel * _Nonnull)panel;
@end


SWIFT_CLASS("_TtC8ZoomUnit12ZMHomeButton")
@interface ZMHomeButton : PZPTrackingButton
@property (nonatomic, strong) NSImage * _Nullable image;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) NSRect focusRingMaskBounds;
- (void)drawFocusRingMask;
@end


@interface ZMHomeButton (SWIFT_EXTENSION(ZoomUnit))
- (void)mouseEntered:(NSEvent * _Nonnull)event;
- (void)mouseExited:(NSEvent * _Nonnull)event;
- (void)mouseDown:(NSEvent * _Nonnull)event;
- (void)mouseUp:(NSEvent * _Nonnull)event;
@end


SWIFT_CLASS("_TtC8ZoomUnit12ZMImageFrame")
@interface ZMImageFrame : NSObject
@property (nonatomic) NSInteger index;
@property (nonatomic) float duration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ZoomUnit16ZMImageFrameInfo")
@interface ZMImageFrameInfo : NSObject
@property (nonatomic) NSInteger frameCount;
@property (nonatomic, copy) NSArray<ZMImageFrame *> * _Nullable gifIndexDurations;
@property (nonatomic) float gifTotleDuration;
@property (nonatomic) float minFrameInterval;
@property (nonatomic) CGSize imagePixSize;
@property (nonatomic) CGImagePropertyOrientation orientation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSColor;

SWIFT_CLASS("_TtC8ZoomUnit18ZMMenuTableRowView")
@interface ZMMenuTableRowView : NSTableRowView
@property (nonatomic, strong) NSColor * _Nullable selectionColor;
@property (nonatomic, strong) NSColor * _Nullable bgColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)drawSelectionInRect:(NSRect)dirtyRect;
- (void)drawBackgroundInRect:(NSRect)dirtyRect;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8ZoomUnit23ZMLightMenuTableRowView")
@interface ZMLightMenuTableRowView : ZMMenuTableRowView
@property (nonatomic, readonly) NSBackgroundStyle interiorBackgroundStyle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZMMLogModule, closed) {
  ZMMLogModuleInvalid = 1000,
  ZMMLogModuleZoom = 1001,
  ZMMLogModuleApp = 1002,
  ZMMLogModuleVideo = 1003,
  ZMMLogModuleAudio = 1004,
  ZMMLogModuleScreenshare = 1005,
  ZMMLogModuleUI = 1006,
  ZMMLogModuleCommon = 1007,
  ZMMLogModuleWebService = 1008,
  ZMMLogModuleAnnotation = 1009,
  ZMMLogModuleSipphone = 1010,
  ZMMLogModuleSipphoneCCI = 1011,
  ZMMLogModuleTp = 1012,
  ZMMLogModuleUtil = 1013,
  ZMMLogModuleCPTHost = 1014,
  ZMMLogModuleCPTShare = 1015,
  ZMMLogModuleNYDUS = 1016,
  ZMMLogModuleMCM = 1017,
  ZMMLogModuleViper = 1018,
  ZMMLogModuleZLT = 1019,
  ZMMLogModuleZMB = 1020,
  ZMMLogModuleZTscoder = 1021,
  ZMMLogModuleQOS = 1022,
  ZMMLogModuleTroubleshoot = 1023,
  ZMMLogModuleAirHost = 1024,
  ZMMLogModulePhonePT = 1025,
  ZMMLogModuleWhiteboards = 1026,
  ZMMLogModuleNotes = 1027,
  ZMMLogModuleDocs = 1028,
  ZMMLogModuleCall = 1029,
  ZMMLogModuleSDK = 1030,
  ZMMLogModuleSession = 1031,
  ZMMLogModuleMediaClient = 1032,
  ZMMLogModuleVideoSDK = 1033,
  ZMMLogModuleMMR = 1034,
  ZMMLogModuleZC = 1035,
  ZMMLogModuleCC = 1036,
  ZMMLogModuleTelephony = 1037,
  ZMMLogModuleSwitch = 1038,
  ZMMLogModuleP2P = 1039,
  ZMMLogModuleP2PSVR = 1040,
  ZMMLogModuleFEC = 1041,
  ZMMLogModuleMonitor = 1042,
  ZMMLogModuleLogControlGW = 1043,
  ZMMLogModuleAudioEngine = 1044,
  ZMMLogModuleBFCP = 1045,
  ZMMLogModuleCMR = 1046,
  ZMMLogModuleRecorder = 1047,
  ZMMLogModuleTunnel = 1048,
  ZMMLogModuleLSGW = 1049,
  ZMMLogModuleLSBOX = 1050,
  ZMMLogModuleSysCodec = 1051,
  ZMMLogModuleZZHost = 1052,
  ZMMLogModuleAudioSDK3RD = 1053,
  ZMMLogModuleZZHost3RD = 1054,
  ZMMLogModuleTxt = 1055,
  ZMMLogModuleHeraSDK = 1056,
  ZMMLogModuleZoomTask = 1057,
  ZMMLogModuleMeetingDetail = 1058,
  ZMMLogModuleDiagnostic = 1059,
  ZMMLogModuleTotalModuleNumber = 1256,
};

typedef SWIFT_ENUM(NSInteger, ZMMemLogLevel, closed) {
  ZMMemLogLevelInfo = 0,
  ZMMemLogLevelError = 1,
  ZMMemLogLevelWarning = 2,
};


SWIFT_CLASS("_TtC8ZoomUnit19ZMMenuTableCellView")
@interface ZMMenuTableCellView : NSTableCellView
@property (nonatomic) CGFloat leftPadding;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly, getter=isFlipped) BOOL flipped;
- (void)updateTitle:(NSString * _Nonnull)title;
@end



SWIFT_CLASS("_TtC8ZoomUnit23ZMNoFocusRingScrollView")
@interface ZMNoFocusRingScrollView : NSScrollView
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class CALayer;

SWIFT_CLASS("_TtC8ZoomUnit12ZMPlayerView")
@interface ZMPlayerView : NSView
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (CALayer * _Nonnull)makeBackingLayer SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL mouseDownCanMoveWindow;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)updateTrackingAreas;
- (void)mouseMoved:(NSEvent * _Nonnull)event;
- (void)mouseExited:(NSEvent * _Nonnull)event;
- (void)keyDown:(NSEvent * _Nonnull)event;
@end



SWIFT_CLASS("_TtC8ZoomUnit9ZMTabView")
@interface ZMTabView : NSTabView
@property (nonatomic, strong) NSColor * _Nullable backgroundColor;
- (void)drawRect:(NSRect)dirtyRect;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ZoomUnit11ZMTextLayer")
@interface ZMTextLayer : CALayer
@property (nonatomic, copy) NSString * _Nullable string;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable attributes;
- (void)drawInContext:(CGContextRef _Nonnull)ctx;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ZMUniversalTipViewDelegate;
@class ZMLabel;

SWIFT_CLASS("_TtC8ZoomUnit18ZMUniversalTipView")
@interface ZMUniversalTipView : ZMBaseView
@property (nonatomic, weak) id <ZMUniversalTipViewDelegate> _Nullable delegate;
@property (nonatomic, strong) NSImage * _Nullable decorativeImage;
@property (nonatomic, strong) ZMLabel * _Nonnull titleField;
@property (nonatomic, strong) ZMLabel * _Nonnull informationField;
@property (nonatomic) BOOL showClose;
@property (nonatomic) BOOL showNew;
@property (nonatomic) BOOL showBeta;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


@interface ZMUniversalTipView (SWIFT_EXTENSION(ZoomUnit))
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title information:(NSString * _Nullable)information;
- (void)setTitleMuiltipleLineModeWithMaxWidth:(CGFloat)titleMaxWidth;
- (void)updteTipViewWithTitle:(NSString * _Nonnull)title information:(NSString * _Nonnull)information;
- (void)updateTitle:(NSString * _Nonnull)title;
- (void)updateInformation:(NSString * _Nonnull)information;
- (void)configActionButtonsWithPrimaryButtonTitle:(NSString * _Nullable)primaryButtonTitle primaryButtonAction:(void (^ _Nullable)(void))primaryButtonAction secondaryButtonTitle:(NSString * _Nullable)secondaryButtonTitle secondaryButtonAction:(void (^ _Nullable)(void))secondaryButtonAction;
@end



SWIFT_PROTOCOL("_TtP8ZoomUnit26ZMUniversalTipViewDelegate_")
@protocol ZMUniversalTipViewDelegate
@optional
- (void)chatTabTipViewClose:(ZMUniversalTipView * _Nonnull)tipView;
@end


SWIFT_CLASS("_TtC8ZoomUnit11ZPHUDWindow")
@interface ZPHUDWindow : NSPanel
@property (nonatomic, readonly) BOOL canBecomeKeyWindow;
- (nonnull instancetype)initWithContentRect:(NSRect)contentRect styleMask:(NSWindowStyleMask)style backing:(NSBackingStoreType)backingStoreType defer:(BOOL)flag OBJC_DESIGNATED_INITIALIZER;
+ (BOOL)accessibilityIsIgnored SWIFT_WARN_UNUSED_RESULT;
- (void)invisibleInSharing;
@end

@class NSTimer;
@class ZPHUDWindowModel;
@class ZPHUDWindowManager;

SWIFT_CLASS("_TtC8ZoomUnit21ZPHUDWindowController")
@interface ZPHUDWindowController : NSWindowController
@property (nonatomic, strong) NSTimer * _Nullable timer;
@property (nonatomic) BOOL inFadeoutProcess;
@property (nonatomic, strong) ZPHUDWindowModel * _Nullable model;
@property (nonatomic) BOOL clicked;
@property (nonatomic, strong) ZPHUDWindowManager * _Nullable manager;
- (nonnull instancetype)initWithWindow:(NSWindow * _Nullable)window OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZPHUDWindowController (SWIFT_EXTENSION(ZoomUnit))
+ (ZPHUDWindowController * _Nonnull)createHUDWindowWithModel:(ZPHUDWindowModel * _Nullable)model manager:(ZPHUDWindowManager * _Nullable)manager SWIFT_WARN_UNUSED_RESULT;
- (void)updateDescFieldForChatMessage:(NSString * _Nullable)theDesc;
@end

@class PZMToastView;
@class NSTextField;

@interface ZPHUDWindowController (SWIFT_EXTENSION(ZoomUnit))
- (void)windowDidLoad;
+ (void)awakeFromNib;
- (void)initHUDWindow SWIFT_METHOD_FAMILY(none);
- (void)displayPrismToastView;
- (void)initTimer SWIFT_METHOD_FAMILY(none);
- (void)clickView;
- (void)startFadeout;
- (void)onFadeoutTimer;
- (void)onTimer;
- (void)relayoutWindowHeight:(PZMToastView * _Nullable)toastView;
- (void)recalWindowHeight:(NSTextField * _Nullable)theField;
- (void)closeHudWindow;
- (void)cleanUp;
@end


SWIFT_CLASS("_TtC8ZoomUnit18ZPHUDWindowManager")
@interface ZPHUDWindowManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZPHUDWindowManager * _Nonnull sharedInstance;)
+ (ZPHUDWindowManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) NSTimer * _Nullable timer;
@property (nonatomic) BOOL ignoreNormalMessage;
@property (nonatomic, copy) NSArray<ZPHUDWindowController *> * _Nonnull controllers;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface ZPHUDWindowManager (SWIFT_EXTENSION(ZoomUnit))
- (void)cleanupHudWindows;
- (ZPHUDWindowController * _Nullable)lastObjectInControllers SWIFT_WARN_UNUSED_RESULT;
- (ZPHUDWindowController * _Nullable)hudWindowControllerWithFriendId:(NSString * _Nullable)friendId SWIFT_WARN_UNUSED_RESULT;
- (void)onTimer;
@end


@interface ZPHUDWindowManager (SWIFT_EXTENSION(ZoomUnit))
- (void)resetManager;
- (void)showWithHUDWindowModel:(ZPHUDWindowModel * _Nullable)model;
- (void)removeHudWindowModel:(ZPHUDWindowModel * _Nullable)model;
- (void)removeHudWindowItem:(ZPHUDWindowController * _Nullable)item;
- (void)ignoreMessageAtStart;
@end


SWIFT_CLASS("_TtC8ZoomUnit16ZPHUDWindowModel")
@interface ZPHUDWindowModel : NSObject
@property (nonatomic, copy) NSString * _Nullable friendId;
@property (nonatomic, copy) NSString * _Nonnull photoUrl;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, weak) id _Nullable target;
@property (nonatomic) SEL _Nullable action;
@property (nonatomic) BOOL isLongDesc;
@property (nonatomic) BOOL isPresenceChangeMessage;
@property (nonatomic) BOOL isPTChatMessage;
@property (nonatomic) float fadeoutSeconds;
@property (nonatomic) BOOL photoIsAvatar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PZMCheckboxView;

SWIFT_CLASS("_TtC8ZoomUnit15ZPHUDWindowTool")
@interface ZPHUDWindowTool : NSObject
+ (PZMToastView * _Nonnull)pzmHudToastViewWithTitle:(NSString * _Nullable)title body:(NSString * _Nonnull)body imageFileName:(NSString * _Nonnull)imageFileName toastDidClicked:(void (^ _Nullable)(void))toastDidClicked closeButtonDidClicked:(void (^ _Nullable)(void))closeButtonDidClicked SWIFT_WARN_UNUSED_RESULT;
+ (PZMToastView * _Nonnull)pzmHudToastViewWithTitle:(NSString * _Nullable)title body:(NSString * _Nonnull)body imageFileName:(NSString * _Nonnull)imageFileName linkButtonaName:(NSString * _Nullable)linkButtonaName linkButtonaDidClicked:(void (^ _Nullable)(void))linkButtonaDidClicked linkButtonDisplayInPrimary:(BOOL)linkButtonDisplayInPrimary checkboxLabel:(NSString * _Nullable)checkboxLabel onCheckBoxStateChange:(void (^ _Nullable)(PZMCheckboxView * _Nullable, BOOL))onCheckBoxStateChange toastDidClicked:(void (^ _Nullable)(void))toastDidClicked closeButtonDidClicked:(void (^ _Nullable)(void))closeButtonDidClicked SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
